// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stream": {
            "get": {
                "description": "Opens a long-lived NDJSON stream of FIEs. Slow consumers are lapped\nautomatically.",
                "produces": [
                    "application/x-ndjson"
                ],
                "tags": [
                    "stream"
                ],
                "summary": "Stream forwarding info elements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SequencedFIE"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Agent": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                }
            }
        },
        "api.IPVersion": {
            "type": "integer",
            "format": "int32",
            "enum": [
                4,
                6
            ],
            "x-enum-varnames": [
                "IPv4",
                "IPv6"
            ]
        },
        "api.Info": {
            "type": "object",
            "properties": {
                "probe_ttl": {
                    "type": "integer"
                },
                "received_timestamp": {
                    "type": "string"
                },
                "reply_address": {
                    "description": "ReplyAddress is the IP address in the reply (e.g., router interface address).",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sent_timestamp": {
                    "type": "string"
                }
            }
        },
        "api.Protocol": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                17,
                58
            ],
            "x-enum-varnames": [
                "ICMP",
                "UDP",
                "ICMPv6"
            ]
        },
        "api.SequencedFIE": {
            "type": "object",
            "properties": {
                "agent": {
                    "$ref": "#/definitions/api.Agent"
                },
                "destination_address": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "far_info": {
                    "$ref": "#/definitions/api.Info"
                },
                "ip_version": {
                    "$ref": "#/definitions/api.IPVersion"
                },
                "near_info": {
                    "$ref": "#/definitions/api.Info"
                },
                "probing_directive_id": {
                    "description": "ProbingDirectiveID links this result to its originating directive.",
                    "type": "integer"
                },
                "production_timestamp": {
                    "description": "ProductionTimestamp is when this record was created (not when probes were sent).",
                    "type": "string"
                },
                "protocol": {
                    "$ref": "#/definitions/api.Protocol"
                },
                "sequence_number": {
                    "type": "integer"
                },
                "source_address": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "iprl.dioptra.io",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "IP Routes Live API",
	Description:      "Streams forwarding info elements collected by Retina agents.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
